services:
  auth:
    image: nhost/hasura-auth:0.38.0
    depends_on:
      graphql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      AUTH_ACCESS_CONTROL_ALLOWED_EMAIL_DOMAINS: ''
      AUTH_ACCESS_CONTROL_ALLOWED_EMAILS: ''
      AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS: ''
      AUTH_ACCESS_CONTROL_BLOCKED_EMAIL_DOMAINS: ''
      AUTH_ACCESS_CONTROL_BLOCKED_EMAILS: ''
      AUTH_ACCESS_TOKEN_EXPIRES_IN: '900'
      AUTH_ANONYMOUS_USERS_ENABLED: 'false'
      AUTH_API_PREFIX: /v1
      AUTH_CLIENT_URL: http://localhost:3000
      AUTH_CONCEAL_ERRORS: 'false'
      AUTH_DISABLE_NEW_USERS: 'false'
      AUTH_DISABLE_SIGNUP: 'false'
      AUTH_EMAIL_PASSWORDLESS_ENABLED: 'false'
      AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED: '${AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED}'
      AUTH_GRAVATAR_DEFAULT: blank
      AUTH_GRAVATAR_ENABLED: 'true'
      AUTH_GRAVATAR_RATING: g
      AUTH_HOST: 0.0.0.0
      AUTH_JWT_CUSTOM_CLAIMS: '{}'
      AUTH_LOCALE_ALLOWED_LOCALES: en
      AUTH_LOCALE_DEFAULT: en
      AUTH_MFA_ENABLED: 'false'
      AUTH_MFA_TOTP_ISSUER: ''
      AUTH_OTP_EMAIL_ENABLED: 'false'
      AUTH_PASSWORD_HIBP_ENABLED: 'false'
      AUTH_PASSWORD_MIN_LENGTH: '9'
      AUTH_PORT: '4000'
      AUTH_RATE_LIMIT_BRUTE_FORCE_BURST: '10'
      AUTH_RATE_LIMIT_BRUTE_FORCE_INTERVAL: 5m
      AUTH_RATE_LIMIT_EMAIL_BURST: '10'
      AUTH_RATE_LIMIT_EMAIL_INTERVAL: 1h
      AUTH_RATE_LIMIT_EMAIL_IS_GLOBAL: 'true'
      AUTH_RATE_LIMIT_ENABLE: 'true'
      AUTH_RATE_LIMIT_GLOBAL_BURST: '100'
      AUTH_RATE_LIMIT_GLOBAL_INTERVAL: 1m
      AUTH_RATE_LIMIT_SIGNUPS_BURST: '10'
      AUTH_RATE_LIMIT_SIGNUPS_INTERVAL: 5m
      AUTH_RATE_LIMIT_SMS_BURST: '10'
      AUTH_RATE_LIMIT_SMS_INTERVAL: 1h
      AUTH_REFRESH_TOKEN_EXPIRES_IN: '2592000'
      AUTH_REQUIRE_ELEVATED_CLAIM: disabled
      AUTH_SERVER_URL: http://${AUTH_URL}/v1
      AUTH_SMTP_AUTH_METHOD: LOGIN
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PASS: password
      AUTH_SMTP_PORT: '1025'
      AUTH_SMTP_SECURE: 'false'
      AUTH_SMTP_SENDER: hasura-auth@example.com
      AUTH_SMTP_USER: user
      AUTH_TURNSTILE_SECRET: ''
      AUTH_USER_DEFAULT_ALLOWED_ROLES: user,me
      AUTH_USER_DEFAULT_ROLE: user
      HASURA_GRAPHQL_ADMIN_SECRET: ${GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${JWT_SECRET}
      POSTGRES_MIGRATIONS_CONNECTION: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    extra_hosts:
      - host.docker.internal:host-gateway
      - ${AUTH_URL}:host-gateway
      - ${DB_URL}:host-gateway
      - ${FUNCTIONS_URL}:host-gateway
      - ${GRAPHQL_URL}:host-gateway
      - ${STORAGE_URL}:host-gateway
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -S
        - http://localhost:4000/healthz
      timeout: 60s
      interval: 5s
      start_period: 60s
    labels:
      traefik.enable: 'true'
      traefik.http.routers.auth.entrypoints: web
      traefik.http.routers.auth.rule: Host(`${AUTH_URL}`)
      traefik.http.routers.auth.service: auth
      traefik.http.routers.auth.tls: 'false'
      traefik.http.services.auth.loadbalancer.server.port: '4000'
    restart: always
    volumes:
      - type: bind
        source: nhost/emails
        target: /app/email-templates
        read_only: false
